// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sample.Templates
{
    using T4FileGenerator.BaseTemplate;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\ClassLibraries\T4FileGenerator\Sample\Sample\Templates\SampleTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SampleTemplate : BaseTemplate<Models.Sample>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\r\nHello World Fool\r\n\r\n");
            
            #line 7 "P:\ClassLibraries\T4FileGenerator\Sample\Sample\Templates\SampleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 12 "P:\ClassLibraries\T4FileGenerator\Sample\Sample\Templates\SampleTemplate.tt"

    public override string RelativeFilePath => $"{Model.Name}.cs";

        
        #line default
        #line hidden
    }
    
}
